name: travel_buddy
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  flutter_launcher_icons: ^0.9.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/fonts/
    - assets/svg/

  fonts:
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/San-Francisco-Pro-Fonts/SF-Pro-Display-Bold.otf
        - asset: assets/fonts/San-Francisco-Pro-Fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/San-Francisco-Pro-Fonts/SF-Pro-Display-Semibold.otf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/Logo.png"
  remove_alpha_ios: true
  color: "#000000"
  foreground_color: "#ffffff"
  icon_size: 100
